# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: flatiron_mod3_development

test:
  <<: *default
  database: flatiron_mod3_test

production:
  <<: *default
  database: flatiron_mod3_production